# Brief: This workflow initializes the upstream repository by pushing the type commits
# Note: Must be run on the default branch

name: Init

on:
  workflow_dispatch: # Enables manual triggering

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

jobs:

  init:
    
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Create root commits for all the supported types, and tag them as such
        env:
          GIT_AUTHOR_NAME: 'a a' # Repeats letter for compression
          GIT_AUTHOR_EMAIL: 'a@a.a' # Repeats letter in name for compression
          GIT_AUTHOR_DATE: '1735689600 +0000' # 2025-01-01T00:00:00.000Z
          GIT_COMMITTER_NAME: 'a a' # Repeats author name for compression
          GIT_COMMITTER_EMAIL: 'a@a.a' # Repeats author email for compression
          GIT_COMMITTER_DATE: '1735689600 +0000' # Repeats author date for compression
        run: |
          git init
          touch value
          ln value value.txt
          ln value value.json
          refspec=''
          for type in 'Number' 'Boolean' 'String' 'JSON' 'Blob' 'ArrayBuffer'; do
            git checkout --orphan="${type}"
            echo -n "${type}" > value
            git add value*
            git commit --allow-empty-message -m ''
            refspec+="+refs/heads/${type}:refs/tags/kv/types/${type} "
          done
          git remote add origin \
            "https://${GITHUB_REPOSITORY_OWNER}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
          git push --force origin ${refspec}